version: '3.8'

services:
  php-fpm:
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - shared_volume:/speedtest/
      - html_volume:/var/www/html
    command: php-fpm -F

  apache:
    image: php:7.4-apache
    ports:
      - "80:80"
    volumes:
      - shared_volume:/speedtest/
      - html_volume:/var/www/html
      - ./apache.conf:/etc/apache2/conf-available/apache.conf
      - ./docker/servers.json:/servers.json
      - ./favicon.ico:/var/www/html/favicon.ico
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`147.45.50.15.nip.io`)"
      - "traefik.http.services.apache.loadbalancer.server.port=80"
      - "traefik.http.middlewares.add-forwarded-host.headers.customrequestheaders.X-Forwarded-Host=${host}"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: apache

  postgres:
    image: postgres
    container_name: my_postgres_container
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - shared_volume:/speedtest/
      - db_volume:/var/lib/postgresql/data
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: postgres

  traefik:
    image: "traefik:v2.5"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: traefik

volumes:
  shared_volume:
  html_volume:
  db_volume:

